#version: '3.8'
services:
  modbus_app:
    build: .
    container_name: modbus_app
    restart: always
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: bridge
